---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: "4.47.3"
  url: oci://ghcr.io/prometheus-community/charts/prometheus-node-exporter
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: node-exporter
    namespace: monitoring
  values:
    fullnameOverride: node-exporter
    hostNetwork: false
    image:
      registry: quay.io
      repository: prometheus/node-exporter
    prometheus:
      monitor:
        enabled: true
