keys:
  - &flux age19k33axf7wxxvzhqddsnlsgqfuedtu4jqd9u0kyqfn7emw7dnndfqmqaqx3
  - &jagd_makani age1f2tqnz4ja42u9apjfl9yhjdp45zmpzjhupdzjecr2765spq955xqrvnq00

creation_rules:
  - path_regex: ^talos/(.*.ya?ml|talosconfig)$
    encrypted_regex: "((?i)(pass|secret($|[^N])|ca|crt|key|token|^data$|^stringData$))"
    key_groups:
      - age:
          - *flux
          - *jagd_makani
