# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: default
stringData:
  adminUsername: ENC[AES256_GCM,data:v1hZdA==,iv:XBAThw6ok2RVNoUUv7bY8PJzwNc/Yimy7YPuREaejoc=,tag:rT1u2r6cETM8YH7LU9RiRQ==,type:str]
  adminPassword: ENC[AES256_GCM,data:FIiuMKsNNGYqzwJAST7HVXs5VkY=,iv:shhO7vvj08aQBKlUliMYezbtWz1VSLgmUt/S1MVoV3Y=,tag:3eNVmzPSW4kxdgAfbvqhaw==,type:str]
sops:
  age:
    - recipient: age1359hy5a889g8ut40tyz9q9fvr06p2x74j8c2khfaqgjnvar6waus6e97dy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbWQ5eG9GNEFDWVhaNjJW
        dUQrK3p6THEzZGNiTkRDNDRQWEhhVTVKdlVNCmEyVTR3NDAra0NGd3hGYkZlTTQ2
        SUx4VUoxbEh4U2lZNlFvVmRJWlg3MmcKLS0tIHorZWRIdU1vd3VRQkllbnZpeXZC
        ekcyTm9VbTJUYStzOVJhWFZZNGZzUkEKmyz82YXLgGzcvNEYhSet/QD16Sr/3AaU
        OPpD2rFUh0X3lSywM/Aux0GjwQRfQ7+WwX1zb6xWUnTM/Lt9Ylv+pA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1f2tqnz4ja42u9apjfl9yhjdp45zmpzjhupdzjecr2765spq955xqrvnq00
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOFBaMnZuMXc2dVdGUXZi
        ZnNKZVlRenkzeEM3a2dSNXlmRGZkSHczcVNJCi9QUmVJSXJUV3Y1SWFSQUM4SGhL
        ODg5aVVKUEdsRDZRbzJVQlNvR0x4SmcKLS0tIEFXYnhjVGhVcDVNSXpZNGZrczVZ
        RzdFR2xzUzNHc1FkK1RNUm1HSmhZN28K3WUPjKTXyMHZV2oL65BDXgLD+A6exqci
        t+S1mJCBXg/vfSCRhR85nTLe3v2OilHh8Q2nTGFOQMRMzOrBEGYmWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-20T17:04:35Z"
  mac: ENC[AES256_GCM,data:5+2g/8Xw7wBNyQgWGc6bsYAdvpKg0hjTwhj9z9A9jaObhR9zPmVC2LI53BxEr9+1HhF/aa15SnLZ2rAUyAl8kGtTcM70xA4+7wEFNo9FVU/+/g27f4sqLeNCWvH7LkMqdE+DHMVR/NO8iPZPUnfZ38gMAmN7gZ0Wx3f7PLtjG/o=,iv:KvZQD9vAVxYYbdOvNTgXDLuZy67J77YPVardG7WqIio=,tag:/vpdwvtbzJepdai9LpJNog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
