---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: ${APP}-nightly
  namespace: database
spec:
  schedule: "${DB_BACKUP_JITTER:=0} 30 3 * * *"
  backupOwnerReference: self
  cluster:
    name: postgresql-16
  immediate: true
