---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${APP}
spec:
  instances: ${DB_INSTANCES:=1}
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4-4
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: openebs-hostpath
    size: ${DB_SIZE:=5Gi}
  superuserSecret:
    name: ${APP}-cloudnative-pg-superuser
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: ${DB_NAME:=${APP}}
      owner: ${DB_USER:=${APP}}
      secret:
        name: ${APP}-db-user
