---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./b2credentials.sops.yaml
  - ./backup.yaml
  - ./cluster.yaml
  - ./superuser.sops.yaml
