---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${VOLSYNC_VOLUME_NAME:-${APP}}-volsync
stringData:
  RESTIC_REPOSITORY: s3:${VOLSYNC_B2_BASE}/${VOLSYNC_VOLUME_NAME:-${APP}}
  RESTIC_PASSWORD: ${VOLSYNC_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${VOLSYNC_B2_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${VOLSYNC_B2_SECRET_ACCESS_KEY}
