---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${VOLSYNC_VOLUME_NAME:-${APP}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${VOLSYNC_VOLUME_CAPACITY}
  storageClassName: nfs-csi
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: ${VOLSYNC_VOLUME_NAME:-${APP}}-rdst
