---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${VOLSYNC_VOLUME_NAME:-${APP}}-rdst
spec:
  trigger:
    manual: restore-once
  restic:
    accessModes: [ReadWriteOnce]
    cacheStorageClassName: openebs-hostpath
    capacity: ${VOLSYNC_VOLUME_CAPACITY}
    cleanupCachePVC: true
    cleanupTempPVC: true
    copyMethod: Snapshot
    repository: ${VOLSYNC_VOLUME_NAME:-${APP}}-volsync
    storageClassName: nfs-csi
    volumeSnapshotClassName: nfs-csi
