---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
components:
  - ../../components/common
resources:
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./kube-state-metrics/ks.yaml
  - ./node-exporter/ks.yaml
