---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  CLUSTER_SECRETS_FILE: "kubernetes/components/common/sops/cluster-secrets.sops.yaml"

tasks:
  cmd:
    desc: Run an arbitrary `restic` command [APP=required] [CMD=required]
    dir: "{{.ROOT_DIR}}"
    cmd: restic {{.CMD}}
    vars:
      REPOSITORY_BASE:
        sh: sops exec-file {{.CLUSTER_SECRETS_FILE}} 'yq ".stringData.VOLSYNC_B2_BASE" {}'
    env:
      AWS_ACCESS_KEY_ID:
        sh: sops exec-file {{.CLUSTER_SECRETS_FILE}} 'yq ".stringData.VOLSYNC_B2_ACCESS_KEY_ID" {}'
      AWS_SECRET_ACCESS_KEY:
        sh: sops exec-file {{.CLUSTER_SECRETS_FILE}} 'yq ".stringData.VOLSYNC_B2_SECRET_ACCESS_KEY" {}'
      RESTIC_PASSWORD:
        sh: sops exec-file {{.CLUSTER_SECRETS_FILE}} 'yq ".stringData.VOLSYNC_RESTIC_PASSWORD" {}'
      RESTIC_REPOSITORY: s3:{{.REPOSITORY_BASE}}/{{.APP}}
    requires:
      vars: [APP]

  dump:
    desc: Dump a backup to a local folder [APP=required] [TARGET=required] [SNAPSHOT]
    cmds:
      - task: cmd
        vars:
          APP: "{{.APP}}"
          CMD: restore {{.SNAPSHOT}} --target {{.TARGET}}
    vars:
      SNAPSHOT: '{{.SNAPSHOT | default "latest" }}'
    requires:
      vars: [APP]

  list:
    desc: List backup snapshots [APP=required]
    cmds:
      - task: cmd
        vars:
          APP: "{{.APP}}"
          CMD: snapshots
    requires:
      vars: [APP]
