apiVersion: v1
kind: Secret
metadata:
  name: external-dns-unifi-secret
  namespace: external-dns
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:A3Ein3dXT/vGjevf,iv:ZOv81aACIA9YYCEkxMM7nsxjF1/0nDW/iUBiXFkTnrw=,tag:mYnjFI9cBTPGiNGHh6lwIw==,type:str]
  password: ENC[AES256_GCM,data:pJsq4ZIpCulKC8EgVO12hyutLcA=,iv:G1L7gZ+hHQUIXSaYeK3rKYMMWSdcmZjSN7ht1Lqh1Ys=,tag:h8TAXAp3bqAuo6ZRGdylsw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19k33axf7wxxvzhqddsnlsgqfuedtu4jqd9u0kyqfn7emw7dnndfqmqaqx3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbkREZjhjWXROalZQelYv
        VVhMYlRCRU5odjVPakZ2OU0xcEtEMHhjd0E0CmdMZEphcTFXK25uN2tmcW5paWpa
        TmFVbXRwNnV6WHV3di8vMDk2ZXdGeFkKLS0tIEhBL2JULzZPRWlKUDNlSXNSWkor
        dGxnK01sbHFGNUdVSUdYVGQ3LzJqKzQKwvQJH1uguDUvxBjSvFp1FzAsZwqmFknq
        aw5ytqQnNoQcpEt8d+19CpzQPJqc8v7xOk9OpOxtl0ut5aSB1DRPWg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1f2tqnz4ja42u9apjfl9yhjdp45zmpzjhupdzjecr2765spq955xqrvnq00
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdEc2aHlGclpjaE9jRXJJ
        NHk1b0J4Y2wwQUloejkxdGlzcWh6ZGZUNGg0CmVxeGVwQjhaVnNpekNDZWk4Vmpl
        UGN3ZTRQc1BJYUUvNmJZTFp0eS90WFkKLS0tIGpqYVZFUjZIZVd5c0s1bVlzMHhV
        N2dJblZoUVFYbTM5cXUvRlVOQjMrVlEKJACaEPVJJbt0cqR4viuiy5hGL9Wno4hu
        AeybNZZ8NP/DHLEYpIGsVqvBqYgIAYB+U06+zuov1k3wSChjGs+s7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-02T09:11:35Z"
  mac: ENC[AES256_GCM,data:0uwHx8VVL9YAAbhUKG3XLN0i4EGoLqJ+OYcXiEH6pL/QtyByAXFvbT06gtsn5+MzVDdiGZkNixhiobIp3BxuSrUmIPQGsCSP3jdF53u7nm9UiXW65r1lZymS9YJWOglVOIs75paCY2xK2uqVtBS6+1fkI6rWV8aN9x9FZx8vsdI=,iv:iW9pEVpE+G1Wk/xxeef950S8Vjlb6GREL21hUr6ydIU=,tag:2/4e3NOy2nZtSM82RbLl4w==,type:str]
  pgp: []
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
  version: 3.9.1
