apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
    namespace: external-dns
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:yhei7jIUHqR/Z6FK,iv:NyduyyIJelIui8Qn60gjhm2iermW1vM9TWhoCMg03FQ=,tag:RyMc3ozRcuBph+Kkg+Kn6g==,type:str]
    password: ENC[AES256_GCM,data:7uY2OpNzprJL01GOociT/8UcwWI=,iv:QYiU5X6UodNP7XPCxmPgVWFEh0NQ4691oG2L9lmsxlI=,tag:j8hZNTEIbyOZbtwv2cE33w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19k33axf7wxxvzhqddsnlsgqfuedtu4jqd9u0kyqfn7emw7dnndfqmqaqx3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TDVlam9WK1hzUUxkZE92
            NEh6UkpLdVVyS1FXVk1velpaZ2JMSUhMMEZjCjZ5ODVOTm8zbldZRWVJRmpoUjBE
            M2JtN1pReWVJT0FrejY3ZW9NWEtwaTAKLS0tIGNWOXYrRHhnU2pJTGcvU1Q0czIx
            YURmTlEyZjEvSXhVMlMxK2orYm9QWU0K/ZmUA9A/G6NKK5H2dxh3QdJvZ4cJfQsj
            qUevSSy/6w8iDjyxD7tHW8XnwprUMMruTATN7d1pTCRyRuuaGdu1EA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f2tqnz4ja42u9apjfl9yhjdp45zmpzjhupdzjecr2765spq955xqrvnq00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWW9YRW4rM2Q1emZ1N2k3
            QW1xMy9KTzRDTXpHNGg5eG1TV2ZCY0kxYnk0CklSZWlla1M5L2VCNnBCR01rWWlI
            SWd2Ymw2amQ2MTk2VkNZbXhqS2RWVmcKLS0tIHlwWWdZdUQxbFJUY1dZSTJHWGxG
            Rm12d2huWDAwbXh2UnVHM3RobUZPRFEKVYGDFhOALPo/kmRRj3L2fRiHVP13ZNil
            2B3PH5xtMeuaGu6xlvFJWhTKBK4x352SEwzIUml4ovg7l/HTGUQ7NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T08:36:08Z"
    mac: ENC[AES256_GCM,data:XDEBZYTH5f2nBJ3ZuL00ODDvhtcjJlw8dLx2hotif0L/UJpKhQmdlp2HYV64D5Kxi+5Kusv4eE8PdJiiJ2/hKmWyLM3ziIShrqjqxrbqGARth2+1ihb76eVxtj1vab/b1izI7VGQ7r9CAJDZNIoSevpI0/9Ma6Z/W85j7DSAdvQ=,iv:2i+6efq1jyHcPhHPQshoBe34WwzNj9FDuOrUuE2ac60=,tag:1l1AOJRd1cMwYey39lqRqA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData$))
    version: 3.9.1
