---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-db
  namespace: database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4-4
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: openebs-hostpath
    size: 10Gi
  superuserSecret:
    name: cloudnative-pg-superuser
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: paperless-db-user
