# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:KfkkNHiCl2g8Nwcv2jRO3Xc3gY9C+DO0mp1gJBUbry4=,iv:u6VUQrAdgNvU/9JnYsUYxpgsnm+/bTrbEvQmxcz19IA=,tag:/bq5BK8IFNFEORuolxNOtg==,type:str]
sops:
  age:
    - recipient: age1359hy5a889g8ut40tyz9q9fvr06p2x74j8c2khfaqgjnvar6waus6e97dy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbG4vczFNRGpxaVVlcE5v
        MUhmaHhsUDhjRzBUd2Rwa3JxendmSUN2dlNBCktCRW1QZTAxUEErWmQydDhLM2VX
        NFN4Q2FPaU5jUVYvUW54TmFjK0oyQ3MKLS0tIFVGQnoyRVhzcGRFdk01MUpJbVV6
        V3FaQ0g3dTNnT0NuSWFDNi9lYVl6ZGsKQMqjZ9gpYfARJqPguWZUgng1kkyGjwpJ
        BrIM7f4cK7AnJVP480Ufs8ajR5bYTyFpJT5gKWUlFMXzmdegKAziww==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1f2tqnz4ja42u9apjfl9yhjdp45zmpzjhupdzjecr2765spq955xqrvnq00
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YVdWc0tUL001Y3YycFZB
        VHJzOFZha0t2ZFkvcVRLQWI2SDE3VFpEU0ZRCkhjQXE4SHNmVGp6dWk1NEVJakZC
        eVdpVWhscjdWWUNDMnJCZVJETWZmVk0KLS0tIG5MYVFxOEZCSnZ1V0RMOTNud1M3
        bEs2TVRtVkNhK0tjMmRmaUtYdFFxODAKCyBaX9lCYWFm+cuNfXVIOs6bx1zJkEBo
        WvzbBTphusJzp7vhXIUx1YhtNqBSNKNHopwuIXDzbNkIgXA/OPRqjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-12T13:14:35Z"
  mac: ENC[AES256_GCM,data:CWy4oMpA8C5+eA6S+G2x+iiooTtIP+TnJPVv/IVJsPvc5k+kOKoukWdaAWftUJIDB8a7DhcMILsBUp3nrk2WjIcUNcpXdq4XmnlxQvzkrIBZKzp+91pcU7Zo2Pq/D003FTv1v592JpU7HaPKNaG6eIcH9aa/CPVklNA6l1Krjok=,iv:6p3EXbPiklHbFtaLvHGFzYq3wIE2vultCBeBTsrmmqQ=,tag:zBfTDd9dTMPoJeuN1OJ/aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
