---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "75.12.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    alertmanager:
      route:
        main:
          hostnames: ["alertmanager.${SECRET_DOMAIN}"]
          parentRefs:
            - name: internal
              namespace: kube-system
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: openebs-hostpath
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
    grafana:
      route:
        main:
          hostnames: ["grafana.${SECRET_DOMAIN}"]
          parentRefs:
            - name: internal
              namespace: kube-system
    prometheus:
      route:
        main:
          hostnames: ["prometheus.${SECRET_DOMAIN}"]
          parentRefs:
            - name: internal
              namespace: kube-system
      prometheusSpec:
        retentionSize: 15GiB
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: openebs-hostpath
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
